config/routes.rb
Rails.application.routes.draw do
  root 'alchemy#index'

  get 'alchemy/results'
  post 'alchemy/results'

end

app/models/result.rb
class Result < ActiveRecord::Base
end

app/controllers/alchemy_controller.rb
class AlchemyController < ApplicationController
	



  def index
	end



  def results

  # Calls all previous entries in Result table and deletes them 
  	@results = Result.all
  	@results.delete_all
  	@ticker = params[:ticker]

  # Encode the given URL to be sent to the AlchemyAPI	

  	encodeUrl = URI.encode("#{params[:ticker]}", /(?!\.)\W/)
					
					puts "Encoded URL: #{encodeUrl}"

 					#Strips off the beginning double quotation marks 
					oldUrl = "#{encodeUrl}".gsub("%5B%22","")
					puts oldUrl


					# Strips of the ending double quotation marks
					myUrl = oldUrl.gsub("%22%5D","")
					puts myUrl
					myTarget = "#{params[:target]}"
					
#  Must use your own API Key
					apikey = "#{ENV['alchemyapi_key']}"


					puts "#{myTarget}"
					puts "#{myUrl}"
					puts myUrl


				 	alcquery = "http://gateway-a.watsonplatform.net/calls/url/URLGetTargetedSentiment?target=#{myTarget}&url=" + "#{myUrl}" + "&apikey=" + apikey + "&outputMode=json&showSourceText=1&sourceText=cleaned"
					
					puts alcquery
					
# Hits the AlchemyAPI
					response = RestClient.get(alcquery)


	# 'response' is parsed in to 'alcresult' and collected into an table called "Result".
					alcresult = JSON.parse(response)
						

					if alcresult["status"] != "ERROR"
						result = Result.new
						result.target = @target
						result.urltext = alcresult["text"]
						result.url = params[:ticker]
						result.senttype = alcresult["docSentiment"]["type"]
						result.score = alcresult["docSentiment"]["score"]
						result.save

#Tests that the appropriate output was  parsed via the terminal						
						puts alcresult["url"], alcresult["docSentiment"]["type"], alcresult["docSentiment"]["score"]

						
					end

					@results = Result.all
				






  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/alchemy_helper.rb
module AlchemyHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alchemy/index.html.erb
<h1>Check the sentiment of a URL text based on a term</h1>
<p id="notice"><%= notice %></p>
<div>

<!-- Request a URL and search term from user -->
	<%= form_tag alchemy_results_path do %>
		<%= text_field_tag :ticker, nil, placeholder: "Enter the URL" %>
		<%= text_field_tag :target, nil, placeholder: "Enter the term to search" %>
		<br>
		<!-- Results are sent to the "results" page -->
		<%= submit_tag "Check Sentiment" %>
	<% end %>
</div>

app/views/alchemy/results.html.erb
<h1>Sentiment Result</h1>

<!-- Results are shown -  url, sentiment type and sentiment score -->
<% @results.each do |r|%>
	<p>Url searched:	<%= link_to "#{r.url}", "#{r.url}", :target => "_blank" %></p>
	<p>Sentiment Type: <%= r.senttype %></p> 
	<p>Sentiment Score: <%= r.score %></p>
<% end %>	

<!-- Enter another query -->

<%= link_to 'Submit another URL and Term', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlcTest</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>